name: cct_management
description: "App for logistic management"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  #Manage svg files
  flutter_svg: ^2.0.10+1
  # lottie files
  lottie: ^3.1.2
  # shared preference to caching variables
  shared_preferences: ^2.2.3
  # class for routing app pages
  go_router: ^14.1.4
  # to load skeleton loadings
  skeletonizer: ^1.4.1+1
  # riverpod dependencies
  flutter_riverpod: ^2.5.1
  date_field: ^5.2.1
  riverpod_annotation: ^2.3.5
  http: ^1.2.1
  # dependencia para objetos deserializables DTOs
  json_annotation: ^4.9.0
  flutter_input_chips: ^1.0.3
  fluttertoast: ^8.2.6
  input_quantity: ^2.3.4
  flutter_flavorizr: ^2.2.3 # use for app flavors
  connectivity_plus: ^6.0.3 #validate internet connection
  intl: any
  stack_trace: any
  logger: any
  package_info_plus: ^8.0.0 #device information
  url_launcher: ^6.3.0 #use for launch hyperlinks
  flutter_localization: ^0.2.2
  flutter_secure_storage: ^9.2.2
  sqflite: ^2.0.0+4 # For SQLite database operations
#  path: ^1.9.1       # For handling file paths
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0
  # dependencia dev para objetos deserializables DTOs
  json_serializable: ^6.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/froggy_banner.jpeg
    - assets/warehouse.png
    - assets/logo.png
    - assets/maintainance/no_internet.json
    - assets/maintainance/maintenance.json
    - assets/logos/
    - assets/logos/cct_logo.png
    - assets/logos/atheneox.png
    - assets/maintainance/settings.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
fonts:
 - family: Ubuntu
   fonts:
     - asset: assets/fonts/Ubuntu-Regular.ttf
       style: normal
     - asset: assets/fonts/Ubuntu-Bold.ttf
       style: bold
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true # TODO: poner en false cuando no se agreguen nuevos textos
  main_locale: es
  class_name: S # TODO: puede llamarse app_localization
    #arb_dir: lib/l10n
  #output_dir: lib/generated
