// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQX23SbE0OpBLZm_FgcEj0Rte5UfrzZEY',
    appId: '1:450051229221:web:e4e4617cced8c0bb1261cc',
    messagingSenderId: '450051229221',
    projectId: 'neoxprojects-007',
    authDomain: 'neoxprojects-007.firebaseapp.com',
    databaseURL: 'https://neoxprojects-007.firebaseio.com',
    storageBucket: 'neoxprojects-007.appspot.com',
    measurementId: 'G-DG22K72GV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGi4BERayNUatFhsk54PrlC0ekTQznPLc',
    appId: '1:450051229221:android:0ca6e93ef47765b81261cc',
    messagingSenderId: '450051229221',
    projectId: 'neoxprojects-007',
    databaseURL: 'https://neoxprojects-007.firebaseio.com',
    storageBucket: 'neoxprojects-007.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChpQ-Yh-ybiwD_jUQ-cmwZHe5CtnM57wU',
    appId: '1:450051229221:ios:ae975163dbdcaedc1261cc',
    messagingSenderId: '450051229221',
    projectId: 'neoxprojects-007',
    databaseURL: 'https://neoxprojects-007.firebaseio.com',
    storageBucket: 'neoxprojects-007.appspot.com',
    androidClientId: '450051229221-vb83d0sk0ke176cikca42ttnseovgvq9.apps.googleusercontent.com',
    iosClientId: '450051229221-2vshqntjqorscgq80cdqet31gfbh7qke.apps.googleusercontent.com',
    iosBundleId: 'com.atheneox.parkea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChpQ-Yh-ybiwD_jUQ-cmwZHe5CtnM57wU',
    appId: '1:450051229221:ios:ae975163dbdcaedc1261cc',
    messagingSenderId: '450051229221',
    projectId: 'neoxprojects-007',
    databaseURL: 'https://neoxprojects-007.firebaseio.com',
    storageBucket: 'neoxprojects-007.appspot.com',
    androidClientId: '450051229221-vb83d0sk0ke176cikca42ttnseovgvq9.apps.googleusercontent.com',
    iosClientId: '450051229221-2vshqntjqorscgq80cdqet31gfbh7qke.apps.googleusercontent.com',
    iosBundleId: 'com.atheneox.parkea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQX23SbE0OpBLZm_FgcEj0Rte5UfrzZEY',
    appId: '1:450051229221:web:6e80a30877ee4ba61261cc',
    messagingSenderId: '450051229221',
    projectId: 'neoxprojects-007',
    authDomain: 'neoxprojects-007.firebaseapp.com',
    databaseURL: 'https://neoxprojects-007.firebaseio.com',
    storageBucket: 'neoxprojects-007.appspot.com',
    measurementId: 'G-YDKZY2M4JG',
  );
}
